# EUREKA CLIENT REGISTRATION CONFIG
eureka:
  client:
    healthcheck:
      enabled: 'true'
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    hostname: localhost
    port: '8761'
    
# API GATEWAY CONFIG
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
            
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/shop/**
            
        - id: product-recommendation-service
          uri: lb://product-recommendation-service
          predicates:
            - Path=/review/**
            
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/catalog/**
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    
# SERVER DETAILS
server:
  port: '8900'
