spring:
  # REDIS
  redis:
    host: localhost
    port: '6379'
  application:
    name: order-service
    
  # DATASOURCE
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:orders
    
  # JPA:
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  session:
    store-type: redis
    redis:
      namespace: session
  h2:
    console:
      enabled: 'true'
  sql:
    init:
      mode: always
    
# EUREKA SERVER REGISTRATION
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# SERVER DETAILS
server:
  port: '8812'
  
# FEIGN CLIENTS
# PRODUCT MICROSERVICE NAME
product:
  service:
    name: product-service
# USER MICROSERVICE NAME
user:
  service:
    name: user-service

# LOG ALL HTTP REQUEST
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG