spring:
  application:
    name: product-recommendation-service
  
  # DATASOURCE
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:product_recommendations
    
  # JPA:
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: 'true'
  sql:
    init:
      mode: always

    
# SERVER DETAILS
server:
  port: '8813'
  
# FEIGN CLIENTS
# PRODUCT MICROSERVICE NAME
product:
  service:
    name: product-service
# USER MICROSERVICE NAME
user:
  service:
    name: user-service
    
# LOG ALL HTTP REQUEST
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
