spring:
  application:
    name: product-service
    
  # DATASOURCE
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:products
    
  # JPA:
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: 'true'
  sql:
    init:
      mode: always
      
# EUREKA SERVER REGISTRATION
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
# SERVER DETAILS
server:
  port: '8810'
  
# LOG ALL HTTP REQUEST
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
